#if !defined(_APPLICATION_ERRORS_CODES_H_INCLUDED_)
#define _APPLICATION_ERRORS_CODES_H_INCLUDED_

enum  e_tDataSrcCreationError : UINT
{
	DSCE_OK	= 0x1000L,
	DSCE_NAME_NOT_SET,	
	DSCE_TYPE_NOT_SET,
	DSCE_CHANNEL_NOT_SET,
	DSCE_UNKNOWN_TYPE,
	DSCE_DEVICE_NOT_SET,
	DSCE_DUPLICATE_NAME,
	DSCE_EMPTY_PARAMETR,
	DSCE_INVALID_PARAMETR,
	DSCE_INVALID_DEVICE,		
	DSCE_INVALID_CHANNEL,
	DSCE_INVALID_DS_ID,
	DSCE_INVALID_DS_TYPE,
	DSCE_INVALID_ADS_RANGE,
	DSCE_INVALID_CONVERTER_IN_FORWARD_CHAIN,
	DSCE_INVALID_CONVERTER_IN_REVERSE_CHAIN,
	DSCE_EMPTY_SUBDS_LIST,
	DSCE_LEVEL_NOT_SET,
	DSCE_LOW_RANGE_LEVEL_NOT_SET,
	DSCE_HIGH_RANGE_LEVEL_NOT_SET,
	DSCE_INVALID_FILTER_ID
};

enum e_tDeviceCreationError
{
	DCE_OK	=	0x2000L,
	DCE_DEVICE_TYPE_NOT_SET,
	DCE_UNKNOWN_DEVICE_TYPE,
	DCE_DEVICE_NAME_NOT_SET,
	DCE_INVALID_INTERVAL,
	DCE_DEVICE_ADDRESS_NOT_SET,
	DCE_INVALID_DEVICE_ADDRESS,
	DCE_PORT_NUMBER_NOT_SET,
	DCE_DUPLICATE_NAME,
	DCE_ANOTHER_MODULE_TYPE,
	DCE_PORT_NOT_AVAILABLE,
	DCE_MODULE_NOT_RESPOND,
	DCE_DATA_PROVIDER_NOT_SET,
	DCE_DATA_PROVIDER_NOT_FOUND,
	DCE_CONTROLED_GAS_NOT_SET,
	DCE_INVALID_CONTROLED_GAS,
	DCE_INVALID_CHANNEL_NUMBER,
	DCE_INVALID_DATA
};

enum e_tWatchDogCreationError
{
	WDCE_OK = 0x3000L,
	WDCE_NAME_NOT_SET,
	WDCE_DUPLICATE_ID,
	WDCE_ALREADY_USED,
	WDCE_LISTEN_DS_NOT_SET,
	WDCE_LISTEN_DS_NOT_FOUND,
	WDCE_OUTPUT_DS_NOT_SET, 
	WDCE_OUTPUT_DS_NOT_FOUND, 
	WDCE_OUTPUT_DS_INVALID_TYPE, 
	WDCE_INVALID_ATTRIBUTE, 
	WDCE_ATTRIBUTE_NOT_SET, 
	WDCE_SCRIPT_NOT_SET, 
	WDCE_SCRIPT_NOT_FOUND,
};

enum e_tDrawObjCreationError
{
	DOCE_OK = 0x4000L,
	DOCE_PARAMETER_NOT_DEFINED,	
	DOCE_INVALID_DATA_SRC,
	DOCE_INVALID_PATH,
	DOCE_INVALID_IMAGE_STRIP
};

#endif