//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NanoTubesControlCenter.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDS_CONFIG_LOAD_FAILED          102
#define IDS_SCRIPT_CHECK1               103
#define IDS_SCRIPT_CHECK2               104
#define IDS_SCRIPT_CHECK3               105
#define IDS_SCRIPT_CHECK4               106
#define IDS_SCRIPT_CHECK5               107
#define IDS_SCRIPT_CHECK0               108
#define IDD_AUTOCALC_SIZE               109
#define IDS_APP_CLOSE_FAILURE           109
#define IDS_CHEM_CHECK0                 110
#define IDS_APP_CLOSE_PERMISIONS        111
#define IDS_SCRIPT_RUN_PERMITIONS       112
#define IDS_APP_CLOSE_WITH_ACTIVE_SCRIPTS 113
#define ID_VIEW_UI_LOOK_BAR             114
#define ID_VIEW_PROP_WND                115
#define IDR_MAINFRAME                   128
#define IDR_NANOTUBESCC_TYPE            129
#define IDR_NANOTUBESPROJECT_TYPE       130
#define IDI_ICON_INFO                   131
#define IDR_DS_VIEW_TOOL_BAR            132
#define IDD_DS_VIEW_DLG                 133
#define IDR_SCRIPTS_TOOL_BAR            134
#define IDC_CUR_WE                      136
#define IDC_CUR_ARROW                   137
#define IDC_CUR_LINK                    148
#define IDC_CUR_MOVE                    150
#define IDC_CUR_NESW                    151
#define IDC_CUR_NS                      152
#define IDC_CUR_NWSE                    153
#define IDC_CURS_UP                     154
#define IDR_DS_POPUP_MENU               155
#define IDB_BITMAP_SPLASH               165
#define IDB_BANER                       166
#define IDB_TREE_NET                    167
#define IDB_PROGRESS_BORDER             199
#define IDB_AQUA_PROGRESS               200
#define IDB_BLUE_PROGRESS               201
#define IDB_DARK_BLUE_PROGRESS          202
#define IDB_OFFICE2007_PROGRESS         203
#define IDB_GRAY_PROGRESS               204
#define IDB_GREEN_PROGRESS              205
#define IDB_MAGENTA_PROGRESS            206
#define IDB_ORANGE_PROGRESS             207
#define IDB_RED_PROGRESS                208
#define IDB_VIOLETE_PROGRESS            209
#define IDD_LOADINGDLG                  300
#define IDI_ICON_ERRORS                 303
#define IDI_ICON_WARNING                305
#define IDD_USER_LOGIN                  306
#define IDI_GROUP_ADMINS                307
#define IDI_GROUP_TECHNOLOGISTS         308
#define IDI_GROUP_OPERATORS             309
#define IDI_GROUP_USERS                 310
#define IDD_ADD_APP_USER                311
#define IDB_ON_16x16_V3                 313
#define IDB_OFF_16x16_V3                314
#define IDI_APPLY                       315
#define IDI_APPLY_ALL                   316
#define IDI_PRESETS                     317
#define IDD_PLOT                        318
#define IDR_PLOT_TOOLBAR                319
#define IDC_DS_VIEW_TOOL_BAR            1005
#define IDC_DS_TREE_GRID                1006
#define IDC_SCRIPTS_TOOL_BAR            1007
#define IDC_LIST_SCRIPTS                1009
#define IDC_SCRIPT_TEXT                 1011
#define IDC_GRID                        1124
#define IDC_PLOT_PLACEHOLDER            1124
#define IDC_CHK_IGNORE_ERROR            1125
#define IDC_COMMON_PROGRESS             1126
#define IDC_BANER                       1127
#define IDC_TEXT                        1129
#define IDC_STEP_INFO                   1130
#define IDC_ED_PASSWORD                 1133
#define IDC_BTN_USERS                   1134
#define IDC_BTN_NUM0                    1135
#define IDC_BTN_NUM1                    1136
#define IDC_BTN_NUM2                    1137
#define IDC_BTN_NUM3                    1138
#define IDC_BTN_NUM4                    1139
#define IDC_BTN_NUM5                    1140
#define IDC_BTN_NUM6                    1141
#define IDC_BTN_NUM7                    1142
#define IDC_BTN_NUM8                    1143
#define IDC_BTN_NUM9                    1144
#define IDC_BTN_NUM_DEL                 1145
#define IDC_BTN_NUM_ENTER               1146
#define IDC_BTN_NUM_CLEAR               1147
#define IDC_ED_ULOGIN                   1148
#define IDC_ED_UNAME                    1149
#define IDC_CMB_UGROUP                  1150
#define IDC_ED_UPASS                    1151
#define IDC_ED_UPASSCONFIRM             1152
#define IDC_ED_UPHONE                   1153
#define IDC_XAXIS_MIN                   1153
#define IDC_XAXIS_MAX                   1154
#define IDC_YAXIS_MAX                   1155
#define IDC_YAXIS_MIN                   1156
#define IDC_PLOT_TOOL                   1157
#define IDC_PLOT_TOOLBAR                1157
#define IDC_YAXIS_MAX2                  1158
#define IDC_YAXIS_MIN2                  1159
#define ID_VIEW_MENUBAR                 23366
#define IDD_SCRIPTS_DLG                 23369
#define IDD_DS_OUTPUT_DLG               23370
#define ID_DS_USER_LAYOUT               32774
#define ID_DS_BY_DEVICE_LAYOUT          32775
#define ID_DS_BY_TYPE_LAYOUT            32776
#define ID_SCRIPT_OPEN                  32777
#define ID_SCRIPT_SAVE                  32778
#define ID_SCRIPT_SAVE_ALL              32779
#define ID_SCRIPT_RUN                   32780
#define ID_SCRIPT_STOP                  32781
#define ID_VIEW_DYNAMIC                 32783
#define ID_VIEW_LOAD_RESULTS            32788
#define ID_ADD_USER                     32790
#define ID_LOCK_APP                     32791
#define ID_VIEW_LOG_BAR                 32795
#define ID_SHOW_HINT                    32797
#define ID_DS_BY_SCRIPT_LAYOUT          32799
#define ID_VIEW_CONFIG                  32802
#define ID_VIEW_DEBUG_WND               32804
#define ID_SHOW_LEGEND                  32807
#define ID_BTN_001                      32808
#define ID_SHOW_REGIONS                 32808
#define ID_BTN_002                      32809
#define ID_SHOW_CHEKPOINTS              32809
#define ID_BTN_003                      32810
#define ID_USEAXIS_SLIDER               32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
