//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PlotTester.rc
//
#define IDD_ABOUTBOX				100
#define IDP_OLE_INIT_FAILED			100
#define IDR_MAINFRAME				128
#define IDR_PlotTesterTYPE				129
//#define IDR_MANIFEST				CREATEPROCESS_MANIFEST_RESOURCE_ID



#define ID_VIEW_MENUBAR              23366
#define ID_VIEW_RESIZABLEBAR_EMPTY   23367
#define ID_VIEW_RESIZABLEBAR_TREE    23368
#define ID_VIEW_RESIZABLEBAR_EDIT    23369
#define ID_VIEW_RESIZABLEBAR_CP      23340
#define ID_VIEW_RESIZABLEBAR_DLG     23341
#define IDD_DIALOG_FOR_RESIZABLE_BAR 23342
#define IDC_EDIT_IN_RESIZABLE_FORM   23343



// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	130
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
